### ISSUE TITLE
Problem with permalink containing one line only

### ISSUE THREAD

**Issue by antomor** [yusanshi/embed_like_gist#10]
If I try to generate the code with a permalink that contains one line only, it shows the file from that line up to the end, while we only would show the single line.

**Comment by Nolanrulesroblox** [comment]
What File are you using? can you paste the ``` <script> ```

**Comment by yusanshi** [comment]
You're right. Will be fixed then.

**Comment by yusanshi** [comment]
Fixed, you can check it.

**Comment by antomor** [comment]
Just checked, and it works like a charm 👍 

Thanks for the prompt response!
