### ISSUE TITLE
Embeds Fail to Render After Forking Repository and Using Github Pages

### ISSUE THREAD

**Issue by muonmax** [yusanshi/embed_like_gist#17]
After forking the repository and removing the CNAME file, the code snippet fails to load - it just spins. I have verified that the embed does render correctly on emgithub.com.

See `https://ideon-technologies.github.io/embed-like-gist/ `and testing with `https://github.com/yusanshi/embed-like-gist/blob/master/404.html`

**Comment by yusanshi** [comment]
You are right it is a bug. The code is assuming `embed.js` is always located at website root directory so if you are using a subdirectory (for example, if you didn't set a custom domain in `CNAME`), the `embed.js` will be wrongly located. I have made a fix for this, so you can sync with the main repo using [`Fetch upstream`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) and try again :)

**Comment by yusanshi** [comment]
**Before**
![image](https://user-images.githubusercontent.com/36265606/143976657-2fce5525-323c-4bae-a7e3-22b24fb00a4c.png)



**After**
![image](https://user-images.githubusercontent.com/36265606/143976563-b86a2a97-2164-4f62-b411-cc6ab56c78a5.png)
