### ISSUE TITLE
File does not update

### ISSUE THREAD

**Issue by mvodep** [yusanshi/embed_like_gist#18]
I updated a file:
https://github.com/mvodep/Playground/blob/main/Hibernate%20History/schema.sql

When i insert the URL, the old version is shown:
`<script src="https://emgithub.com/embed.js?target=https%3A%2F%2Fgithub.com%2Fmvodep%2FPlayground%2Fblob%2Fmain%2FHibernate%2520History%2Fschema.sql&style=github&showBorder=on&showLineNumbers=on&showFileMeta=on&showCopy=on&fetchFromJsDelivr=on"></script>`

Line 7 is changed from SERIAL to INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY for example

How long is the file cached?

**Comment by yusanshi** [comment]
In your link,
```
fetchFromJsDelivr=on
```

It seems to be the cache issue of jsDelivr. If you update the files frequently then you may uncheck the `Fetch from jsDelivr` checkbox.

**Comment by yusanshi** [comment]
I have just submitted a commit that makes `fetchFromJsDelivr` option default to unchecked and adds descriptive text. (https://github.com/yusanshi/embed-like-gist/commit/28b8f6d3cd44cb91e1443a28c9876b7cb1731a89)

**Comment by mvodep** [comment]
Thanks a lot - works with this option off. I thought its just for the JS Files and not for the content itself.

Beside that: Very nice project!!!
