### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'querySelector') at embed-v2.js:422:33

### ISSUE THREAD

**Issue by InCogNiTo124** [yusanshi/embed_like_gist#23]
I'm trying to embed my own code in a website:

https://github.com/InCogNiTo124/avgen/blob/master/avgen.py

pasting the generated script:

`<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2FInCogNiTo124%2Favgen%2Fblob%2Fmaster%2Favgen.py&style=default&type=code&showBorder=on&showLineNumbers=on&showFileMeta=on&showFullPath=on&showCopy=on"></script>`

generates an error from the title.

**Comment by InCogNiTo124** [comment]
Note: this works without any problems

```html
<html>
  <head>
  </head>
  <body>
      <script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2FInCogNiTo124%2Favgen%2Fblob%2Fmaster%2Favgen.py&style=default&type=code&showBorder=on&showLineNumbers=on&showFileMeta=on&showFullPath=on&showCopy=on"></script>
  </body>
</html>
```

However, I can't even come up with how could the error be produced.

**Comment by yusanshi** [comment]
Which website is the code embedded in? Could you provide a screenshot?

Also, you can try to embed code from GitHub Gist:

``` 
<script src="https://gist.github.com/…"></script>
 ```

Emgithub works in a way very similar to GitHub Gist. If GitHub Gist does not work on that website, so would Emgithub.

**Comment by InCogNiTo124** [comment]
> Emgithub works in a way very similar to GitHub Gist. If GitHub Gist does not work on that website, so would Emgithub.

thank's for the suggestion @yusanshi . I tried it out and it fails, too.

The error shows in my custom blogging platform and the origin of the error seems to be using `.innerHTML` somwhere in the code while loading the page, which prevents the script from running. I've yet to confirm  my hypothesis (or come up with an alternative implementation).

**Comment by yusanshi** [comment]
Thanks for the feedback. I believe it should be related to how the blogging platform works. Sorry but I can't help with it. I'll close the issue since emgithub is not meant to do more than GitHub Gist.
