### ISSUE TITLE
[feature request] Add dark mode option for markdown files

### ISSUE THREAD

**Issue by DSPaul** [yusanshi/embed_like_gist#30]
The choice of different colour schemes only applies to raw code, the markdown colour scheme is hardcoded to `https://cdn.jsdelivr.net/gh/sindresorhus/github-markdown-css@5.1.0/github-markdown-light.min.css`. There exists a dark mode equivalent `https://cdn.jsdelivr.net/gh/sindresorhus/github-markdown-css@5.1.0/github-markdown-dark.min.css` and it would be nice to have the choice to use that one instead.

**Comment by yusanshi** [comment]
It sounds interesting... But the background color for the embeded markdown is white, so I wonder it may look strange to put the dark code on the white background. What do you think? :thinking:

**Comment by DSPaul** [comment]
Couldn't you just change the background to a dark color in that case? I haven't look to much at your code but all the color schemes for "raw code" change the background color already so I assume there is also a way to do that for the markdown background or am I overlooking something?

**Comment by yusanshi** [comment]
I may need some time to investigate this. Sorry but I'm busy on other stuff these days.

**Comment by DSPaul** [comment]
No worries, it's not a pressing issue anyway, just a nice to have.
