### ISSUE TITLE
Spaces indentation lost

### ISSUE THREAD

**Issue by glepretre** [yusanshi/embed_like_gist#34]
Hi, there is a mystery somewhere: 

When previewing a simple HTML file https://emgithub.com/pajasevi/CSSnowflakes/blob/master/snippet.html everything looks fine,

But when I try to embed it, I lose all indentation. There is nothing but the `<script>`, no CSS, etc.

![image](https://github.com/yusanshi/emgithub/assets/5930831/4ef14f39-b896-4237-9622-73bbbd2f418f)

Do you reproduce?

**Comment by yusanshi** [comment]
![image](https://github.com/yusanshi/emgithub/assets/36265606/5a355616-4c3b-4b29-a462-867763f89cee)

Yes but if you enclose it inside regular `<!DOCTYPE html> <html>... <body> </body></html>` it should looks normal.

(Note the `<!DOCTYPE html>` is necessory. Refer: https://stackoverflow.com/questions/6076432/why-do-i-need-a-doctype-what-does-it-do )

**Comment by glepretre** [comment]
@yusanshi Thanks for finding this out! :pray:
