### ISSUE TITLE
[Feature Request] Support multiple languages

### ISSUE THREAD

**Issue by okatu-loli** [yusanshi/embed_like_gist#39]
For example, support text display in Chinese, Japanese, or other languages

**Comment by yusanshi** [comment]
Do you mean the display language in <https://emgithub.com/>? Sorry but I personally believe this is not a necessary feature. It doesn't make much sense to the core feature of emgithub.com. If you need it really, please refer to <https://github.com/yusanshi/emgithub?tab=readme-ov-file#create-your-own-emgithub>.

**Comment by okatu-loli** [comment]
Understood, thank you
