### ISSUE TITLE
Rendering the script tag version

### ISSUE THREAD

**Issue by oleteacher** [yusanshi/embed_like_gist#41]
Nice work! Using in the classroom and it works great.

I do not understand how to get the <script> version to render on a page? The page is always blank but viewing source I see the script like:

`<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2Fyusanshi%2Femgithub%2Fblob%2Fmaster%2Fembed.js&style=night-owl&type=code&showBorder=on&showLineNumbers=on&showFileMeta=on&showFullPath=on&showCopy=on"></script>`

I assume the script should render but perhaps I am misunderstanding.

**Comment by yusanshi** [comment]
> I do not understand how to get the <script> version to render on a page?

Have you used https://gist.github.com/? Basically emgithub works in the same way as gist. You need to paste `<script src="..."></script>` to the target page (static blog, wordpress, etc).

You can provide more info if help is needed (e.g., what is the target page).

**Comment by oleteacher** [comment]
Thank you for reply @yusanshi. Do not know why not working on our internal school network, no dev errors or anything so cannot troubleshoot. Simply does not display the <script> version. iFrame of course works.

I just tested on a server outside the school network and the <script> version does in fact work, no issues at all.

Closing this and sorry about the false alert :)
