### ISSUE TITLE
Feature request: copy shortcut

### ISSUE THREAD

**Issue by hcientist** [yusanshi/embed_like_gist#9]
Would it be interesting to you/others to add little sharing shortcuts? Like maybe an icon to copy, or an icon to facilitate sharing?

**Comment by yusanshi** [comment]
What do you mean by "sharing"? Share what? Could you give an example of the scenario?

Thx!

**Comment by Nolanrulesroblox** [comment]
> What do you mean by "sharing"? Share what? Could you give an example of the scenario?

I think @hcientist  means like Share button on top of the Frame says something like "share this code on *!" or like click to copy?

Example:
------------------REPO NAME ETC -------- Copy/Share ----
1 - echo "hi"
2 - echo "clear"

user Presses:

Copy - Copy all text from 1 to 2 to Clipboard

Share - Copy Github link to clipboard (not to raw, just to repo - branch - file)

**Comment by yusanshi** [comment]
Thanks! I'll add a "help wanted" label

**Comment by yusanshi** [comment]
Update: @cfurrow and I added the button to copy (#12)

Mouse cursor hovering on the code block but away from the copy button:
![image](https://user-images.githubusercontent.com/36265606/114552232-f2f37100-9c96-11eb-9473-39e1b84371d3.png)

Mouse cursor hovering on the copy button (hmm, the screenshot doesn't take the cursor in):
![image](https://user-images.githubusercontent.com/36265606/114552266-ff77c980-9c96-11eb-9745-acca0954ac54.png)

**Comment by yusanshi** [comment]
Close inactive (and partially resolved) issue. Reopen if needed :)
